security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                target: app_login  # Redirection après déconnexion

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_BANNED: [ROLE_USER]

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        - { path: ^/verify, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/discussion, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: '^/book/new$', roles: ROLE_ADMIN }
        - { path: '^/book/\d+/edit$', roles: ROLE_ADMIN }
        - { path: '^/book/\d+/delete$', roles: ROLE_ADMIN }
        - { path: '^/author/new$', roles: ROLE_ADMIN }
        - { path: '^/author/\d+/edit$', roles: ROLE_ADMIN }
        - { path: '^/author/\d+/delete$', roles: ROLE_ADMIN }
        - { path: '^/genre/new$', roles: ROLE_ADMIN }
        - { path: '^/genre/\d+/edit$', roles: ROLE_ADMIN }
        - { path: '^/genre/\d+/delete$', roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10